{% set name = "thrift" %}
{% set version = "0.16.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/apache/thrift/archive/refs/tags/v{{ version }}.tar.gz
  sha256: df2931de646a366c2e5962af679018bca2395d586e00ba82d09c0379f14f8e7b

build:
  number: 0
  script: {{ PYTHON }} -m pip install ./lib/py -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
  host:
    - pip
    - python
    - setuptools
    - six >=1.7.2
    - wheel
  run:
    - python
    - six >=1.7.2
  run_constrained:
    - tornado >=4.0

test:
  imports:
    - thrift
    - thrift.protocol
    - thrift.server
    - thrift.transport
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://thrift.apache.org
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  license_url: https://github.com/apache/thrift/blob/master/LICENSE
  description: |
    Thrift is a lightweight, language-independent software stack for point-to-point RPC implementation.
    Thrift provides clean abstractions and implementations for data transport, data serialization, and application level processing.
  summary: Python bindings for the Apache Thrift RPC system
  dev_url: https://github.com/apache/thrift
  doc_url: https://thrift.apache.org/docs/
  doc_source_url: https://github.com/apache/thrift/tree/v{{ version }}/doc

extra:
  recipe-maintainers:
    - mariusvniekerk
    - ericdill
    - marshall245
