{% set version = "0.15.0" %}
{% set hash_type = "sha256" %}
{% set hash = "87c8205a71cf8bbb111cb99b1f7495070fbc9cabb671669568854210da5b3e29" %}
{% set name = "thrift" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  {{ hash_type }}: {{ hash }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - six >=1.7.2

  run:
    - python
    - six >=1.7.2

test:
  imports:
    - thrift
    - thrift.protocol
    - thrift.server
    - thrift.transport

about:
  home: http://thrift.apache.org
  license: Apache 2.0
  summary: 'Python bindings for the Apache Thrift RPC system'

extra:
  recipe-maintainers:
    - mariusvniekerk
    - ericdill
    - marshall245
