travis:
  secure:
    BINSTAR_TOKEN: SxkD3htMIqucke+ONkKcHyESOOL71ISGemmlT7mA3h+Z/fnRXhCnSo8wFRZ84QszP5BEXhC71bWX7KBZbEzfr1wF6AHMYlIK02x8NOYWuklLKOgallS0koy/nEU3c0OhXEmeaHy748Txxl/Z5biFxKyl2rrxIQguapy9N5BCfhN8I0C9Zo43UAa8vn+I08mzwHr0SI7JhU4c3mV8dhJIXiM+BJrEw3c+vpkWY568q329/RoJSEJlPPYsPVfzWtTgZpU3cn8vg1gHQcJNStjK7mSspncNpqBWLgrr6gGsKjjAx0jzyOYGo7BWTD/BMKKafF7vuDkH8xcanvIznYWTAbrpFvenWkrrgmpGD4Xxec7lBAfAHMkRuLNi5fWGSZOuc7t+7ctVxkFfkZRNqOdwJLKgC0rGDiitsBO3voM9n0giUfzOGpchgnEj1JMeImPy87qx97nCw7GhJCIzHFQm2iAIqKyKK2eSY3c4NovsaWX2jVwyjFQzQ1j84yWnsIjzyRWlgG5V4relE6YYWbQh3ZFSD0cA8EUZYtJ4HalaaWTmjQgCgluS7iK9BqRsULekOZBkRhXlYF4iiTuhzVH8Vw8CI4Cudq2KUlHPuNFiuFefXFzzgwb1TcYmo1Db4y4n1zsTD0FDM7jFHUHgRwKR/RYX54Wj20QaiU/NIjqrwQ0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
