travis:
  secure:
    BINSTAR_TOKEN: LEwLe1BHXCcomwrjFB7SH9BM9BJtc7AT6i2zHZep/q/lNB+YaMYbAjoOSuIkHAIzesr5TILWiB+SOsNx7ynN+0dViXGwoolTrbAOtQL+K4ux4AvL6KmIgmUJn+QUi2TVexN5WCS4JA7NRLyiJAbse/fEWbjeLVh9HoqTgU7YJZ/kpGmfSUYrC0oLdac20mvRQlmmQinpO3Ch3oYQIPq4z/jMdWQYPKPigBAZNJTQrQTYl+EHMmq/5jTE8iQPmaEKDSbfvpRNtcDtC6NblJQrE6cmASsGAz1O2O41PqLSo1FMipNCMd9UY/jFnkk44/uAp+7FyUBvEfO9RRn1BENjU/5OEIiCFnHp+/sw6t5I6dqT4IsNzr0yQj/cdZ351qVRPxS4LpYI9vbKvfHmwCeAyE/j9A8IPcOCLzupMX3N8kreOGKQuNK8HnBgaSRZDFh8PaN7fXcnVON/WhHx2N6AMz5dzgmZE6BEDAwGRZgBdfWyb9YKKzSL9IqajNCDs2Hqmufh6T1w/2rqaYkIYpFyUVpIQDZaArIpVI7+BIR5+elwG669fVH3ZheWB1ydnfta0GB/cMab+ysJHpjZqfHMOr1bA0aId3OJCj42Ggrx1Tlggr2vNTtisWGVKj84pQq1gt6mVlDU8kZiEyUa3wg1DrjxZUEHEuL4HsHstip2K3s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
